name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: smpio/github-workflows/.github/workflows/docker-customize-image.yaml@master
    with:
      image_name: smpio/python
